plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.tapcard.sample.android.simple'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId 'io.github.tapcard.sample.android.simple.rx2'
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility rootProject.ext.sourceCompatibilityVersion
        targetCompatibility rootProject.ext.targetCompatibilityVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(':tapcard-android')
    implementation deps.rxJava2
    implementation deps.rxJava2Android
    implementation deps.appcompat
    implementation deps.constraintlayout
    testImplementation deps.junit
}
