plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'io.github.tapcard.sample.pcsc.Main'
}

java {
    sourceCompatibility = rootProject.ext.sourceCompatibilityVersion
    targetCompatibility = rootProject.ext.targetCompatibilityVersion
}

dependencies {
    implementation project(':tapcard')
    implementation 'org.slf4j:slf4j-api:1.7.36'
    implementation 'org.slf4j:slf4j-reload4j:1.7.36'
    implementation 'ch.qos.reload4j:reload4j:1.2.22'
}
