plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.tapcard.sample.android'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId 'io.github.tapcard.sample.android'
        minSdk 21
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 28
        versionName '2.1.9'
    }

    compileOptions {
        sourceCompatibility rootProject.ext.sourceCompatibilityVersion
        targetCompatibility rootProject.ext.targetCompatibilityVersion
    }

    buildFeatures {
        buildConfig true
        aidl true
    }

    lint {
        abortOnError false
        textReport true
    }
}

dependencies {
    implementation project(':tapcard')
    implementation deps.appcompat
    implementation 'androidx.fragment:fragment:1.8.6'
    implementation 'androidx.viewpager:viewpager:1.1.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.preference:preference:1.2.1'

    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'commons-io:commons-io:2.15.1'

    implementation 'org.slf4j:slf4j-api:1.7.36'
    implementation 'org.slf4j:slf4j-reload4j:1.7.36'
    implementation 'ch.qos.reload4j:reload4j:1.2.22'

    implementation 'com.readystatesoftware.systembartint:systembartint:1.0.3'
    implementation('de.keyboardsurfer.android.widget:crouton:1.8.5@aar') {
        exclude group: 'com.google.android', module: 'support-v4'
        exclude group: 'com.android.support', module: 'support-v4'
    }
}
